version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reddit_api_development
    volumes:
      - database_cache:/var/lib/postgresql/data

volumes:
  gem_cache:
  database_cache:
